# These are supported funding model platforms

github: #[coco-gene]
patreon: # Replace with a single Patreon username
open_collective: cocojob
ko_fi: # Replace with a single Ko-fi username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
ocomie: # Replace with a single Ocomie username
custom: ['https://www.yunqiic.com/support.html']
